### ISSUE TITLE
Hound doesn't seem to respect Exclude filters

### ISSUE THREAD

**Issue by elsom25** [fog/fog#2948]
If I run Rubocop on the CL, things are evaluated as expected, but Hound continues to yell at many of my PR's.

The parts of my `.hound.yml` of interest:

```
AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/**/*'
    - 'config/environments/**/*'
    - 'config/initializers/devise.rb'
    - 'db/**/*'
    - 'vendor/**/*'

IndentationConsistency:
  Exclude:
    - '**/factories/**/*'

IndentationWidth:
  Exclude:
    - '**/factories/**/*'

RedundantSelf:
  Exclude:
    - '**/models/**/*'
```
